"""Extract the contribution USD and Browser-compatible APKG manifest."""

from __future__ import annotations

import json
import os

import pyblish.api
import hou

from ayon_core.pipeline import PublishError
from ayon_core.pipeline.publish.lib import get_instance_expected_output_path
from ayon_houdini.api import plugin
from ayon_houdini.api.lib import render_rop
from ayon_houdini.api.usd import remap_paths
from ayon_houdini.apkg.models import PackageDependency, PackageResource
from ayon_houdini.apkg.naming import apkg_version_name
from ayon_houdini.apkg.resources import (
    external_resource, plan_resource_transfer,
)
from ayon_houdini.apkg.schema import build_manifest, summary_from_manifest

# Live Pyblish registries may retain the previous ExtractAPKG class whose
# method resolves this global name. Keep the alias so a module reload repairs
# an already-open Houdini session without requiring an application restart.
_external_resource = external_resource


def _resolve_publish_dir(instance, output):
    """Return the APKG version directory from AYON's publish anatomy.

    Core's ``CollectResourcesPath`` does not run for the isolated ``apkg``
    family.  Resolve the entrypoint destination with the same public helper
    used by AYON's USD extractor instead of deriving a path from the work or
    staging directory.
    """
    publish_dir = str(instance.data.get("publishDir") or "").strip()
    if publish_dir:
        return os.path.normpath(publish_dir)

    extension = os.path.splitext(output)[1].lstrip(".") or "usd"
    try:
        expected_output = get_instance_expected_output_path(
            instance,
            representation_name="usd",
            ext=extension,
        )
    except Exception as exc:
        raise PublishError(
            "Could not resolve the APKG publish directory from AYON "
            "anatomy: {}".format(exc)
        ) from exc

    publish_dir = os.path.dirname(str(expected_output or "").strip())
    if not publish_dir:
        raise PublishError(
            "AYON resolved an empty APKG publish directory"
        )
    publish_dir = os.path.normpath(publish_dir)
    instance.data["publishDir"] = publish_dir
    instance.data.setdefault(
        "resourcesDir", os.path.join(publish_dir, "resources")
    )
    return publish_dir


def _resource_from_representation(representation, default_role=None):
    data = representation.get("data") or {}
    name = representation.get("name") or representation.get("ext") or "resource"
    files = representation.get("files") or []
    if isinstance(files, str):
        files = [files]
    staging = representation.get("stagingDir") or ""
    paths = [os.path.join(staging, filename) for filename in files]
    return PackageResource(
        role=data.get("bmfxApkgRole") or default_role or "resource.{}".format(name),
        representation_name=str(name),
        extension=str(representation.get("ext") or ""),
        load_strategy=data.get("bmfxLoadStrategy") or (
            "sublayer" if name == "usd" else "reference"
        ),
        purpose=data.get("bmfxPurpose") or "render",
        paths=tuple(paths),
        tags=tuple(representation.get("tags") or ()),
    )


def _assert_context_not_embedded(output, selection):
    context_paths = [
        str(item.get("entrypointPath") or "")
        for item in selection.get("packages") or []
        if item.get("mode") == "context" and item.get("entrypointPath")
    ]
    if not context_paths:
        return
    needles = {
        path: {
            path.encode("utf-8"),
            path.replace("\\", "/").encode("utf-8"),
        }
        for path in context_paths
    }
    longest = max(len(value) for values in needles.values() for value in values)
    leaked = set()
    tail = b""
    with open(output, "rb") as stream:
        while True:
            chunk = stream.read(1024 * 1024)
            if not chunk:
                break
            payload = tail + chunk
            for path, values in needles.items():
                if any(value in payload for value in values):
                    leaked.add(path)
            if len(leaked) == len(needles):
                break
            tail = payload[-longest:] if longest else b""
    if leaked:
        raise PublishError(
            "Context-only APKG paths leaked into the exported contribution: "
            "{}".format(", ".join(sorted(leaked)))
        )


def _is_apkg_owned_representation(representation):
    """Return whether a representation was generated by this extractor."""
    if not isinstance(representation, dict):
        return False
    tags = set(representation.get("tags") or ())
    data = representation.get("data") or {}
    return (
        representation.get("name") == "apkg"
        or "entrypoint" in tags and "apkg" in tags
        or data.get("bmfxApkgRole") in {"entrypoint", "manifest"}
    )
class ExtractAPKG(plugin.HoudiniExtractorPlugin):
    label = "Extract BMFX APKG"
    order = pyblish.api.ExtractorOrder
    families = ["apkg"]

    def process(self, instance):
        rop_node = hou.node(instance.data["instance_node"])
        source_node = instance.data["output_node"]
        data = instance.data["apkgData"]
        export_rop = (
            rop_node if rop_node.type().name().split("::", 1)[0] == "usd_rop"
            else rop_node.node("usd_export")
        )
        temporary_export_rop = export_rop is None
        if temporary_export_rop:
            # Keep the APKG Publisher as the durable AYON instance and use an
            # invisible, short-lived native USD ROP LOP only for file writing.
            # Nothing is created in /out.
            export_rop = rop_node.parent().createNode(
                "usd_rop", "__bmfx_apkg_export_{}".format(rop_node.sessionId())
            )
            export_rop.setInput(0, source_node)
            export_rop.hide(True)
        configured_output = rop_node.evalParm("lopoutput")
        staging_dir = os.path.dirname(configured_output)
        package_stem = apkg_version_name(
            instance.data["productName"], instance.data.get("version") or 1
        )
        output = os.path.join(staging_dir, package_stem + ".usd")
        rop_node.parm("lopoutput").set(output)
        os.makedirs(staging_dir, exist_ok=True)

        external_paths = data.get("externalResources") or []
        publish_dir = (
            _resolve_publish_dir(instance, output)
            if external_paths else instance.data.get("publishDir")
        )
        resource_mapping = {}
        resource_paths = []
        planned_transfers = []
        for path in external_paths:
            try:
                plan = plan_resource_transfer(path, publish_dir)
            except ValueError as exc:
                raise PublishError(str(exc)) from exc
            resource_paths.append(plan["destination"])
            if plan["source"] != plan["destination"]:
                resource_mapping[plan["source"]] = plan["destination"]
            planned_transfers.extend(plan["transfers"])

        transfers = instance.data.setdefault("transfers", [])
        existing_transfers = {
            (os.path.normpath(src), os.path.normpath(dst))
            for src, dst in transfers
        }
        for source, destination in planned_transfers:
            key = (os.path.normpath(source), os.path.normpath(destination))
            if key not in existing_transfers:
                transfers.append([source, destination])
                existing_transfers.add(key)
        try:
            export_parms = {"lopoutput": output}
            if export_rop.parm("loppath"):
                export_parms["loppath"] = source_node.path()
            if export_rop.parm("flattenstage"):
                # Never flatten inherited APKG content into the contribution.
                export_parms["flattenstage"] = False
            export_rop.setParms(export_parms)
            self.log.info("Writing APKG entrypoint USD: %s", output)
            with remap_paths(export_rop, resource_mapping):
                render_rop(export_rop)
        finally:
            if temporary_export_rop:
                export_rop.destroy()
        if not os.path.isfile(output):
            raise PublishError("APKG entrypoint was not written: {}".format(output))

        _assert_context_not_embedded(output, data["selection"])

        usd_representation = {
            "name": "usd",
            "ext": os.path.splitext(output)[1].lstrip(".") or "usd",
            "files": os.path.basename(output),
            "stagingDir": staging_dir,
            "data": {
                "bmfxApkgRole": "entrypoint",
                "bmfxLoadStrategy": "payload",
                "bmfxPurpose": "render",
            },
            "tags": ["apkg", "entrypoint"],
        }
        representations = instance.data.setdefault("representations", [])
        # Extraction can be retried in the same Publisher session. Remove
        # only this plugin's previous outputs so resources and roles remain
        # unique while unrelated review/proxy representations are preserved.
        representations[:] = [
            representation for representation in representations
            if not _is_apkg_owned_representation(representation)
        ]
        representations.append(usd_representation)

        dependencies = [
            PackageDependency.from_mapping(item)
            for item in instance.data.get("apkgDependencies") or []
        ]
        resources = [
            _resource_from_representation(
                representation,
                default_role=None,
            )
            for representation in representations
            # The root USD is already described by ``manifest.entrypoint``.
            # Treating it as a resource as well makes Browser clients display
            # the package's own staging USD as an upstream dependency.
            if representation is not usd_representation
            and representation.get("name") != "apkg"
        ]
        resources.extend(
            external_resource(path)
            for path in resource_paths
        )

        folder_entity = instance.data.get("folderEntity") or {}
        task_entity = instance.data.get("taskEntity") or {}
        product_entity = instance.data.get("productEntity") or {}
        project_name = instance.context.data["projectName"]
        package_uid = instance.data["bmfxPackageId"]
        manifest = build_manifest(
            package_uid=package_uid,
            project_name=project_name,
            folder_id=folder_entity.get("id", ""),
            task_id=task_entity.get("id", ""),
            department=data["department"],
            role=data["role"],
            slot=data["slot"],
            contribution_type=data["effectType"],
            product_id=product_entity.get("id", ""),
            entrypoint={
                "representationName": "usd",
                "file": os.path.basename(output),
                "defaultPrim": data["exports"][0] if data["exports"] else "",
                "loadStrategy": "payload",
            },
            dependencies=dependencies,
            resources=resources,
            exports=data["exports"],
            requires=data["requires"],
            capabilities=data["capabilities"],
            creator={
                "application": "houdini",
                "houdiniVersion": hou.applicationVersionString(),
                "addon": "ayon_houdini",
            },
            diagnostics={
                "validation": "passed",
                "externalResourceCount": len(resource_paths),
            },
        )
        manifest_name = "{}.apkg.json".format(package_stem)
        manifest_path = os.path.join(staging_dir, manifest_name)
        with open(manifest_path, "w", encoding="utf-8") as stream:
            json.dump(manifest, stream, indent=2, sort_keys=True)
            stream.write("\n")

        representations.append({
            "name": "apkg",
            "ext": "json",
            "files": manifest_name,
            "stagingDir": staging_dir,
            "data": {
                "bmfxApkgRole": "manifest",
                "bmfxApkgSchema": manifest["schema"],
                "bmfxLoadStrategy": "metadata",
            },
            "tags": ["apkg", "manifest"],
        })
        instance.data["apkgManifest"] = manifest
        instance.data.setdefault("versionData", {})["bmfxApkg"] = (
            summary_from_manifest(manifest)
        )
